name: Translate README to French

on:
  push:
    branches:
      - main
      - master

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # Traduction vers le français
      - name: Translate README to French
        uses: dephraiim/translate-readme@main
        with:
          LANG: fr

      # Commit et push automatique
      - name: Commit translated README
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.fr.md
          git commit -m "Add French translated README"
          git push
